export type MinerKey = "gram" | "usdt";

/**
 * A Music NFT: a real, freely licensed song (CC-BY 3.0, Josh Woodward) that
 * doubles as a mining rig. Yields are per day and intentionally realistic —
 * they are quoted against the live market value of GRAM and USDT.
 */
export type NftDef = {
  id: string;
  name: string; // song title
  artist: string;
  album: string;
  license: string;
  audioUrl: string;
  coverUrl: string;
  desc: string;
  /** Daily production of each coin while the NFT is in your collection. */
  musicPerDay: number;
  gramPerDay: number;
  usdtPerDay: number;
  unlocks: MinerKey[];
  stars: number; // Telegram Stars price (0 = not for sale)
  gram: number; // GRAM price (0 = not for sale)
  tone: string; // gradient for the disc label
  rarity: "Free" | "Common" | "Rare" | "Epic" | "Legendary";
  /** Reward-only records are never listed in the shop. */
  reward?: "welcome" | "referral";
};

const A = {
  breadcrumbs: "Breadcrumbs-15322",
  crawford: "Crawford_Street-17897",
  wake: "The_Wake_1790-15241",
} as const;

const audio = (item: string, file: string) => `https://archive.org/download/${item}/${file}`;
const cover = (item: string) => `https://archive.org/services/img/${item}`;

const TONES = [
  "from-sky-400/50 to-cyan-500/10",
  "from-amber-300/50 to-orange-600/10",
  "from-fuchsia-400/50 to-violet-600/10",
  "from-emerald-300/50 to-teal-600/10",
  "from-rose-400/50 to-pink-600/10",
  "from-indigo-400/50 to-blue-700/10",
];

export const NFTS: NftDef[] = [
  {
    id: "welcome-nft",
    name: "Little Tomcat",
    artist: "Josh Woodward",
    album: "The Wake",
    license: "CC BY 3.0",
    audioUrl: audio(A.wake, "Josh_Woodward_-_17_-_Little_Tomcat.mp3"),
    coverUrl: cover(A.wake),
    desc: "Your free welcome record. Mines MUSIC from day one.",
    musicPerDay: 900,
    gramPerDay: 0,
    usdtPerDay: 0,
    unlocks: [],
    stars: 0,
    gram: 0,
    tone: TONES[0]!,
    rarity: "Free",
    reward: "welcome",
  },
  {
    id: "friends-nft",
    name: "I'm Not Dreaming",
    artist: "Josh Woodward",
    album: "Breadcrumbs",
    license: "CC BY 3.0",
    audioUrl: audio(A.breadcrumbs, "Josh_Woodward_-_21_-_Im_Not_Dreaming.mp3"),
    coverUrl: cover(A.breadcrumbs),
    desc: "Free when 5 friends join. Switches GRAM and USDT mining on forever.",
    musicPerDay: 2400,
    gramPerDay: 0.004,
    usdtPerDay: 0.012,
    unlocks: ["gram", "usdt"],
    stars: 0,
    gram: 0,
    tone: TONES[1]!,
    rarity: "Rare",
    reward: "referral",
  },

  /* ---------- Common ---------- */
  {
    id: "swansong",
    name: "Swansong",
    artist: "Josh Woodward",
    album: "Breadcrumbs",
    license: "CC BY 3.0",
    audioUrl: audio(A.breadcrumbs, "Josh_Woodward_-_01_-_Swansong.mp3"),
    coverUrl: cover(A.breadcrumbs),
    desc: "Entry record. Turns on GRAM mining.",
    musicPerDay: 1800,
    gramPerDay: 0.006,
    usdtPerDay: 0.02,
    unlocks: ["gram"],
    stars: 199,
    gram: 0.9,
    tone: TONES[0]!,
    rarity: "Common",
  },
  {
    id: "cherry",
    name: "Cherry",
    artist: "Josh Woodward",
    album: "Crawford Street",
    license: "CC BY 3.0",
    audioUrl: audio(A.crawford, "Josh_Woodward_-_03_-_Cherry.mp3"),
    coverUrl: cover(A.crawford),
    desc: "Bright pop cut with a steady GRAM stream.",
    musicPerDay: 2200,
    gramPerDay: 0.009,
    usdtPerDay: 0.026,
    unlocks: ["gram"],
    stars: 249,
    gram: 1.1,
    tone: TONES[4]!,
    rarity: "Common",
  },
  {
    id: "fight-the-sea",
    name: "Fight the Sea",
    artist: "Josh Woodward",
    album: "Crawford Street",
    license: "CC BY 3.0",
    audioUrl: audio(A.crawford, "Josh_Woodward_-_01_-_Fight_the_Sea.mp3"),
    coverUrl: cover(A.crawford),
    desc: "Warm indie rock. Adds USDT on top of GRAM.",
    musicPerDay: 2600,
    gramPerDay: 0.011,
    usdtPerDay: 0.033,
    unlocks: ["gram", "usdt"],
    stars: 349,
    gram: 1.6,
    tone: TONES[3]!,
    rarity: "Common",
  },
  {
    id: "under-the-stairs",
    name: "Under the Stairs",
    artist: "Josh Woodward",
    album: "Breadcrumbs",
    license: "CC BY 3.0",
    audioUrl: audio(A.breadcrumbs, "Josh_Woodward_-_09_-_Under_the_Stairs.mp3"),
    coverUrl: cover(A.breadcrumbs),
    desc: "Quiet grower with a dependable daily payout.",
    musicPerDay: 3200,
    gramPerDay: 0.014,
    usdtPerDay: 0.041,
    unlocks: ["gram", "usdt"],
    stars: 449,
    gram: 2.1,
    tone: TONES[5]!,
    rarity: "Common",
  },

  /* ---------- Rare ---------- */
  {
    id: "border-blaster",
    name: "Border Blaster",
    artist: "Josh Woodward",
    album: "Breadcrumbs",
    license: "CC BY 3.0",
    audioUrl: audio(A.breadcrumbs, "Josh_Woodward_-_05_-_Border_Blaster.mp3"),
    coverUrl: cover(A.breadcrumbs),
    desc: "Rare pressing. Roughly double a Common record.",
    musicPerDay: 4800,
    gramPerDay: 0.022,
    usdtPerDay: 0.065,
    unlocks: ["gram", "usdt"],
    stars: 699,
    gram: 3.2,
    tone: TONES[1]!,
    rarity: "Rare",
  },
  {
    id: "big-disco-ball",
    name: "Big Disco Ball",
    artist: "Josh Woodward",
    album: "Crawford Street",
    license: "CC BY 3.0",
    audioUrl: audio(A.crawford, "Josh_Woodward_-_07_-_Big_Disco_Ball.mp3"),
    coverUrl: cover(A.crawford),
    desc: "Dancefloor rare with a strong USDT stream.",
    musicPerDay: 5600,
    gramPerDay: 0.026,
    usdtPerDay: 0.078,
    unlocks: ["gram", "usdt"],
    stars: 849,
    gram: 3.9,
    tone: TONES[4]!,
    rarity: "Rare",
  },
  {
    id: "grey-snow",
    name: "Grey Snow",
    artist: "Josh Woodward",
    album: "Breadcrumbs",
    license: "CC BY 3.0",
    audioUrl: audio(A.breadcrumbs, "Josh_Woodward_-_13_-_Grey_Snow.mp3"),
    coverUrl: cover(A.breadcrumbs),
    desc: "Slow burner, heavy on stablecoin output.",
    musicPerDay: 6400,
    gramPerDay: 0.031,
    usdtPerDay: 0.092,
    unlocks: ["gram", "usdt"],
    stars: 999,
    gram: 4.6,
    tone: TONES[5]!,
    rarity: "Rare",
  },
  {
    id: "invisible-light",
    name: "Invisible Light",
    artist: "Josh Woodward",
    album: "The Wake",
    license: "CC BY 3.0",
    audioUrl: audio(A.wake, "Josh_Woodward_-_13_-_Invisible_Light.mp3"),
    coverUrl: cover(A.wake),
    desc: "Rare record with balanced GRAM and USDT yields.",
    musicPerDay: 7400,
    gramPerDay: 0.037,
    usdtPerDay: 0.11,
    unlocks: ["gram", "usdt"],
    stars: 1199,
    gram: 5.5,
    tone: TONES[0]!,
    rarity: "Rare",
  },

  /* ---------- Epic ---------- */
  {
    id: "private-hurricane",
    name: "Private Hurricane",
    artist: "Josh Woodward",
    album: "Breadcrumbs",
    license: "CC BY 3.0",
    audioUrl: audio(A.breadcrumbs, "Josh_Woodward_-_07_-_Private_Hurricane.mp3"),
    coverUrl: cover(A.breadcrumbs),
    desc: "Epic pressing. A serious daily crypto stream.",
    musicPerDay: 11000,
    gramPerDay: 0.055,
    usdtPerDay: 0.165,
    unlocks: ["gram", "usdt"],
    stars: 1799,
    gram: 8.2,
    tone: TONES[2]!,
    rarity: "Epic",
  },
  {
    id: "stars-collide",
    name: "Stars Collide",
    artist: "Josh Woodward",
    album: "Breadcrumbs",
    license: "CC BY 3.0",
    audioUrl: audio(A.breadcrumbs, "Josh_Woodward_-_11_-_Stars_Collide.mp3"),
    coverUrl: cover(A.breadcrumbs),
    desc: "Epic anthem with an outsized USDT payout.",
    musicPerDay: 13500,
    gramPerDay: 0.068,
    usdtPerDay: 0.2,
    unlocks: ["gram", "usdt"],
    stars: 2199,
    gram: 10.1,
    tone: TONES[3]!,
    rarity: "Epic",
  },
  {
    id: "the-spirit-world",
    name: "The Spirit World",
    artist: "Josh Woodward",
    album: "Crawford Street",
    license: "CC BY 3.0",
    audioUrl: audio(A.crawford, "Josh_Woodward_-_11_-_The_Spirit_World.mp3"),
    coverUrl: cover(A.crawford),
    desc: "Dark epic. Big on GRAM, bigger on USDT.",
    musicPerDay: 16000,
    gramPerDay: 0.081,
    usdtPerDay: 0.24,
    unlocks: ["gram", "usdt"],
    stars: 2599,
    gram: 11.9,
    tone: TONES[5]!,
    rarity: "Epic",
  },
  {
    id: "golden-sunrise",
    name: "Golden Sunrise",
    artist: "Josh Woodward",
    album: "The Wake",
    license: "CC BY 3.0",
    audioUrl: audio(A.wake, "Josh_Woodward_-_19_-_Golden_Sunrise.mp3"),
    coverUrl: cover(A.wake),
    desc: "The brightest epic in the collection.",
    musicPerDay: 19000,
    gramPerDay: 0.096,
    usdtPerDay: 0.285,
    unlocks: ["gram", "usdt"],
    stars: 3099,
    gram: 14.2,
    tone: TONES[1]!,
    rarity: "Epic",
  },

  /* ---------- Legendary ---------- */
  {
    id: "overthrown",
    name: "Overthrown",
    artist: "Josh Woodward",
    album: "Breadcrumbs",
    license: "CC BY 3.0",
    audioUrl: audio(A.breadcrumbs, "Josh_Woodward_-_15_-_Overthrown.mp3"),
    coverUrl: cover(A.breadcrumbs),
    desc: "Legendary master. Top-tier crypto yield.",
    musicPerDay: 26000,
    gramPerDay: 0.13,
    usdtPerDay: 0.39,
    unlocks: ["gram", "usdt"],
    stars: 4199,
    gram: 19.3,
    tone: TONES[2]!,
    rarity: "Legendary",
  },
  {
    id: "gemini",
    name: "Gemini",
    artist: "Josh Woodward",
    album: "The Wake",
    license: "CC BY 3.0",
    audioUrl: audio(A.wake, "Josh_Woodward_-_23_-_Gemini.mp3"),
    coverUrl: cover(A.wake),
    desc: "Legendary twin-coin master press.",
    musicPerDay: 31000,
    gramPerDay: 0.155,
    usdtPerDay: 0.46,
    unlocks: ["gram", "usdt"],
    stars: 4899,
    gram: 22.5,
    tone: TONES[0]!,
    rarity: "Legendary",
  },
  {
    id: "2020",
    name: "20/20",
    artist: "Josh Woodward",
    album: "Breadcrumbs",
    license: "CC BY 3.0",
    audioUrl: audio(A.breadcrumbs, "Josh_Woodward_-_03_-_2020.mp3"),
    coverUrl: cover(A.breadcrumbs),
    desc: "The rarest record in the vault.",
    musicPerDay: 38000,
    gramPerDay: 0.19,
    usdtPerDay: 0.56,
    unlocks: ["gram", "usdt"],
    stars: 5999,
    gram: 27.5,
    tone: TONES[4]!,
    rarity: "Legendary",
  },
];

export function nftById(id: string) {
  return NFTS.find((n) => n.id === id) ?? null;
}

/** NFTs the user can actually buy. */
export const SHOP_NFTS = NFTS.filter((n) => !n.reward);
